repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-yaml

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check .
        always_run: true
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy .
        always_run: true
        language: system
        pass_filenames: false
